CREATE TABLE vllm.vllm_buildkite_agents (
    dynamoKey String,
    agent Tuple(
        last_job_finished_at Nullable(DateTime64(3)),
        creator Nullable(String),
        paused Bool,
        created_at DateTime64(3),
        ip_address String,
        connection_state String,
        priority UInt32,
        version String,
        url String,
        cluster_url String,
        hostname String,
        paused_at Nullable(DateTime64(3)),
        web_url String,
        cluster_queue_url String,
        name String,
        meta_data Array(String),
        paused_timeout_in_minutes UInt32,
        id String,
        paused_note Nullable(String),
        job Nullable(
            Tuple(
                retried Bool,
                finished_at Nullable(DateTime64(3)),
                parallel_group_index Nullable(UInt32),
                graphql_id String,
                artifacts_url String,
                step_key Nullable(String),
                created_at DateTime64(3),
                scheduled_at DateTime64(3),
                expired_at Nullable(DateTime64(3)),
                retries_count Nullable(UInt32),
                type String,
                exit_status Nullable(Int32),
                matrix Nullable(String),
                cluster_url String,
                cluster_id String,
                soft_failed Bool,
                retried_in_job_id Nullable(String),
                log_url String,
                retry_source Nullable(String),
                id String,
                state String,
                build_url String,
                retry_type Nullable(String),
                priority Tuple(number UInt32),
                agent_query_rules Array(String),
                command String,
                raw_log_url String,
                cluster_queue_id String,
                web_url String,
                cluster_queue_url String,
                parallel_group_total Nullable(UInt32),
                name String,
                started_at Nullable(DateTime64(3)),
                step Tuple(signature Nullable(String), id String),
                artifact_paths Nullable(String),
                runnable_at DateTime64(3)
            )
        ),
        user_agent String,
        paused_by Nullable(String)
    ),
    event String,
    sender Tuple(name Nullable(String), id Nullable(String))
) ENGINE = SharedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
ORDER BY
    (agent .created_at, agent .name) SETTINGS index_granularity = 8192
