// Auto-generated by scripts/embed-rpc-server.js — do not edit directly.
// To update: edit rpc-server/src/main.rs, run scripts/build-rpc-server.sh,
// then run scripts/embed-rpc-server.js.
//
// Static musl binaries embedded as base64 strings. Selected at runtime by
// rpc.ts based on the target pod's architecture.
//
// This file is committed as a placeholder with empty strings; CI rebuilds
// the binaries and rewrites this file on every build (see the build-rust
// step in .github/workflows/build.yaml). The diff check explicitly excludes
// this file because base64 of a compiled binary is not reproducible across
// rustc patch versions.
/* eslint-disable */
// prettier-ignore
export const RPC_SERVER_AMD64 = ""
// prettier-ignore
export const RPC_SERVER_ARM64 = ""
