#!/usr/bin/env python3
"""
Patch existing torchaudio wheels to remove the runtime CUDA version check.

torchaudio is now built against the PyTorch stable C++ ABI, so the runtime
guard in ``torchaudio/_extension/__init__.py`` that compares the CUDA build
of torchaudio against ``torch.version.cuda`` is no longer needed and blocks
legitimate cross-CUDA-version installs (e.g. torchaudio cu130 wheel on a
torch cu132 install).

This script:
  1. Discovers all torchaudio wheels of a given version under
     https://download.pytorch.org/whl/<channel>/<cuda>/torchaudio
  2. Downloads each wheel.
  3. Removes the ``_check_cuda_version()`` call from
     ``torchaudio/_extension/__init__.py`` inside the wheel. The function
     definition in ``utils.py`` is preserved so external callers (e.g. the
     pytorch/builder smoke test) keep working. RECORD is regenerated by
     auditwheel.
  4. Uploads each patched wheel back to the same locations:
       - AWS S3:  s3://pytorch/whl/<channel>/<cuda>/
       - Cloudflare R2: s3://pytorch-downloads/whl/<channel>/<cuda>/
     Each upload sets ``x-amz-meta-checksum-sha256`` on the object so the
     PEP 503 index pages can pick it up.

Environment variables:
  R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY
        Required to upload to Cloudflare R2. If missing, the R2 upload step
        is skipped with a warning.
  R2_BUCKET_NAME
        R2 bucket name (defaults to ``pytorch-downloads``).

AWS credentials for S3 are picked up from the standard boto3/AWS chain.

Usage:
  python patch_torchaudio_remove_cuda_version_check.py --version 2.11.0 --cuda cu130
  python patch_torchaudio_remove_cuda_version_check.py --version 2.11.0 --cuda cu130 --dry-run
"""

import argparse
import hashlib
import os
import re
import shutil
import sys
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path
from typing import List


DEFAULT_PACKAGE = "torchaudio"
DEFAULT_VERSION = "2.11.0"
DEFAULT_CUDA = "cu130"
DEFAULT_CHANNEL = "test"

INDEX_URL = "https://download.pytorch.org/whl/{channel}/{cuda}/{package}"
DOWNLOAD_BASE = "https://download.pytorch.org/whl/{channel}/{cuda}/{filename}"

S3_BUCKET = "pytorch"
S3_PREFIX = "whl/{channel}/{cuda}"

R2_BUCKET_NAME_DEFAULT = "pytorch-downloads"
R2_PREFIX = "whl/{channel}/{cuda}"

EXTENSION_INIT_PATH = "torchaudio/_extension/__init__.py"
CHECK_CUDA_CALL_RE = re.compile(r"^[ \t]*_check_cuda_version\(\)[ \t]*\n", re.MULTILINE)


def discover_wheels(package: str, version: str, cuda: str, channel: str) -> List[str]:
    """Return list of wheel filenames for ``package`` at ``version`` on the
    given ``channel``/``cuda`` index. Filenames are returned with ``+`` (not
    URL encoded)."""
    index_url = INDEX_URL.format(channel=channel, cuda=cuda, package=package)
    print(f"+ Fetching index: {index_url}")
    with urllib.request.urlopen(index_url) as resp:
        html = resp.read().decode("utf-8", errors="replace")

    pattern = re.compile(
        rf'href="[^"]*?/({re.escape(package)}-{re.escape(version)}'
        rf'(?:%2B|\+){re.escape(cuda)}-[^"#]+\.whl)'
    )
    found = set()
    for match in pattern.finditer(html):
        filename = urllib.parse.unquote(match.group(1))
        found.add(filename)
    wheels = sorted(found)
    print(f"+ Found {len(wheels)} wheel(s) for {package}=={version}+{cuda}")
    return wheels


def download_wheel(filename: str, cuda: str, channel: str, dest_dir: Path) -> Path:
    """Download ``filename`` from the given ``channel``/``cuda`` index into
    ``dest_dir``."""
    url = DOWNLOAD_BASE.format(
        channel=channel, cuda=cuda, filename=urllib.parse.quote(filename)
    )
    dest = dest_dir / filename
    print(f"+ Downloading {url}")
    with urllib.request.urlopen(url) as resp, open(dest, "wb") as out:
        shutil.copyfileobj(resp, out)
    return dest


def patch_wheel(wheel_path: Path, output_dir: Path) -> Path:
    """Remove the ``_check_cuda_version()`` call from
    ``torchaudio/_extension/__init__.py`` inside ``wheel_path`` and write the
    patched wheel into ``output_dir``.

    Uses auditwheel's ``InWheelCtx`` so the RECORD file is regenerated."""
    try:
        from auditwheel.wheeltools import InWheelCtx
    except ImportError:
        print(
            "Error: auditwheel package is not installed. "
            "Install it with 'pip install auditwheel'."
        )
        sys.exit(1)

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_whl = Path(tmp_dir) / wheel_path.name
        with InWheelCtx(wheel_path) as ctx:
            ctx.out_wheel = tmp_whl

            init_file = os.path.join(ctx.path, EXTENSION_INIT_PATH)
            if not os.path.exists(init_file):
                raise RuntimeError(
                    f"{EXTENSION_INIT_PATH} not found in {wheel_path}"
                )

            with open(init_file, "r", encoding="utf-8") as f:
                original = f.read()

            patched, count = CHECK_CUDA_CALL_RE.subn("", original)
            if count == 0:
                raise RuntimeError(
                    f"No _check_cuda_version() call found in "
                    f"{EXTENSION_INIT_PATH} of {wheel_path.name}"
                )
            if count > 1:
                print(
                    f"- WARNING: removed {count} _check_cuda_version() calls "
                    f"from {wheel_path.name} (expected 1)"
                )

            with open(init_file, "w", encoding="utf-8") as f:
                f.write(patched)
            print(
                f"+ Removed _check_cuda_version() call from "
                f"{EXTENSION_INIT_PATH} ({wheel_path.name})"
            )

        out_path = output_dir / wheel_path.name
        if not tmp_whl.exists():
            raise RuntimeError(
                f"auditwheel did not produce expected wheel at {tmp_whl}"
            )
        shutil.move(str(tmp_whl), out_path)
        print(f"+ Patched wheel: {out_path}")
        return out_path


def sha256_of(file_path: Path) -> str:
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def upload_to_s3(
    file_path: Path,
    bucket: str,
    key: str,
    sha256: str,
    dry_run: bool,
) -> None:
    if dry_run:
        print(
            f"+ DRY RUN: would upload {file_path.name} to "
            f"s3://{bucket}/{key} (sha256={sha256})"
        )
        return

    import boto3  # type: ignore[import]

    client = boto3.client("s3")
    print(f"+ Uploading to s3://{bucket}/{key}")
    client.upload_file(
        Filename=str(file_path),
        Bucket=bucket,
        Key=key,
        ExtraArgs={
            "ACL": "public-read",
            "Metadata": {"checksum-sha256": sha256},
        },
    )


def upload_to_r2(
    file_path: Path,
    bucket: str,
    key: str,
    sha256: str,
    dry_run: bool,
) -> None:
    account_id = os.environ.get("R2_ACCOUNT_ID", "")
    access_key = os.environ.get("R2_ACCESS_KEY_ID", "")
    secret_key = os.environ.get("R2_SECRET_ACCESS_KEY", "")
    if not (account_id and access_key and secret_key):
        print(
            "- WARNING: R2 credentials not configured "
            "(R2_ACCOUNT_ID / R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY); "
            "skipping R2 upload"
        )
        return

    if dry_run:
        print(
            f"+ DRY RUN: would upload {file_path.name} to "
            f"R2 s3://{bucket}/{key} (sha256={sha256})"
        )
        return

    import boto3  # type: ignore[import]

    endpoint_url = f"https://{account_id}.r2.cloudflarestorage.com"
    client = boto3.client(
        "s3",
        endpoint_url=endpoint_url,
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name="auto",
    )
    print(f"+ Uploading to R2 s3://{bucket}/{key}")
    client.upload_file(
        Filename=str(file_path),
        Bucket=bucket,
        Key=key,
        ExtraArgs={"Metadata": {"checksum-sha256": sha256}},
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--package", default=DEFAULT_PACKAGE, help="Package name")
    parser.add_argument(
        "--version", default=DEFAULT_VERSION, help="Package version (e.g. 2.11.0)"
    )
    parser.add_argument(
        "--cuda", default=DEFAULT_CUDA, help="CUDA tag (e.g. cu130, cu132)"
    )
    parser.add_argument(
        "--channel",
        default=DEFAULT_CHANNEL,
        choices=("test", "whl", "nightly"),
        help="PyTorch wheel channel (default: test)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Do everything except the actual S3/R2 uploads",
    )
    parser.add_argument(
        "--r2-bucket",
        default=os.environ.get("R2_BUCKET_NAME", R2_BUCKET_NAME_DEFAULT),
        help="R2 bucket name",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    work_dir = Path(tempfile.mkdtemp(prefix="patch-torchaudio-"))
    download_dir = work_dir / "download"
    output_dir = work_dir / "patched"
    download_dir.mkdir(exist_ok=True)
    output_dir.mkdir(exist_ok=True)

    print(f"+ Working directory: {work_dir}")

    try:
        wheels = discover_wheels(args.package, args.version, args.cuda, args.channel)
        if not wheels:
            print(
                f"- No wheels found for {args.package}=={args.version} "
                f"on {args.channel}/{args.cuda}"
            )
            return 1

        s3_prefix = S3_PREFIX.format(channel=args.channel, cuda=args.cuda)
        r2_prefix = R2_PREFIX.format(channel=args.channel, cuda=args.cuda)

        for wheel_filename in wheels:
            downloaded = download_wheel(
                wheel_filename, args.cuda, args.channel, download_dir
            )
            patched = patch_wheel(downloaded, output_dir)
            sha256 = sha256_of(patched)
            print(f"+ sha256({patched.name}) = {sha256}")

            s3_key = f"{s3_prefix}/{patched.name}"
            r2_key = f"{r2_prefix}/{patched.name}"

            upload_to_s3(patched, S3_BUCKET, s3_key, sha256, args.dry_run)
            upload_to_r2(patched, args.r2_bucket, r2_key, sha256, args.dry_run)

        print(f"+ Done. Processed {len(wheels)} wheel(s).")
        print(
            "+ Reminder: regenerate the PEP 503 index for "
            f"whl/{args.channel}/{args.cuda} via "
            "s3_management/manage_v2.py once uploads are complete."
        )
        return 0
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
