#!/usr/bin/env bash

# Make sure to update these versions when doing a release first
PYTORCH_VERSION=${PYTORCH_VERSION:-2.12.1}
TORCHVISION_VERSION=${TORCHVISION_VERSION:-0.27.1}
TORCHAUDIO_VERSION=${TORCHAUDIO_VERSION:-2.11.0}
TORCHCODEC_VERSION=${TORCHCODEC_VERSION:-0.15.0}
TORCHCOMMS_VERSION=${TORCHCOMMS_VERSION:-0.3.1}
TRITON_VERSION=${TRITON_VERSION:-3.7.1}
TORCHTEXT_VERSION=${TORCHTEXT_VERSION:-0.18.0}
TORCHREC_VERSION=${TORCHREC_VERSION:-1.7.0}
EXECUTORCH_VERSION=${EXECUTORCH_VERSION:-1.3.1}
TORCH_TENSORRT_VERSION=${TORCH_TENSORRT_VERSION:-2.12.1}
TORCH_TENSORRT_RTX_VERSION=${TORCH_TENSORRT_VERSION}
TORCHAO_VERSION=${TORCHAO_VERSION:-0.17.0}
TORCHDATA_VERSION=${TORCHDATA_VERSION:-0.11.0}
TORCHTUNE_VERSION=${TORCHTUNE_VERSION:-0.2.1}
FBGEMM_GPU_VERSION=${FBGEMM_GPU_VERSION:-1.7.0}
FBGEMM_GPU_GENAI_VERSION=${FBGEMM_GPU_VERSION}
MSLK_VERSION=${MSLK_VERSION:-1.2.0}
FLASH_ATTN_3_VERSION=${FLASH_ATTN_3_VERSION:-3.0.0}
