#!/usr/bin/env bash

# Make sure to update these versions when doing a release first
PYTORCH_VERSION=${PYTORCH_VERSION:-2.7.0}
TORCHVISION_VERSION=${TORCHVISION_VERSION:-0.24.0}
TORCHAUDIO_VERSION=${TORCHAUDIO_VERSION:-2.9.0}
TRITON_VERSION=${TRITON_VERSION:-3.3.0}
TORCHTEXT_VERSION=${TORCHTEXT_VERSION:-0.18.0}
TORCHREC_VERSION=${TORCHREC_VERSION:-1.4.0}
EXECUTORCH_VERSION=${EXECUTORCH_VERSION:-1.1.0}
TORCH_TENSORRT_VERSION=${TORCH_TENSORRT_VERSION:-2.10.0}
TORCHAO_VERSION=${TORCHAO_VERSION:-0.15.0}
TORCHDATA_VERSION=${TORCHDATA_VERSION:-0.11.0}
TORCHTUNE_VERSION=${TORCHTUNE_VERSION:-0.2.1}
FBGEMM_GPU_VERSION=${FBGEMM_GPU_VERSION:-1.4.1}
FBGEMM_GPU_GENAI_VERSION=${FBGEMM_GPU_VERSION}
MSLK_VERSION=${MSLK_VERSION:-1.0.0}
