#!/usr/bin/env python3
"""
Repackage ROCm torch wheels to fix the intermittent ``import torch`` deadlock
on no-GPU / no-kfd hosts (pytorch/pytorch#189110).

Root cause: rocSHMEM's ``NUMAWrapper`` global constructor does
``dlopen("libnuma.so")`` (the *bare* soname) at library-load time. ROCm 2.13
wheels built by the new manywheel pipeline (pytorch/pytorch#182696) bundle only
the *versioned* ``libnuma.so.1``, so that ``dlopen`` fails, ``NUMAWrapper``
calls ``exit()`` during ``import torch``, and a racy rocprofiler-sdk atexit
``finalize()`` deadlock hangs the import. The old ``build_rocm.sh`` renamed
bundled OS deps to bare sonames, so it never hung.

Fix applied here (same as ``.ci/manywheel/repair_wheel.py`` now does): add
bare-name aliases for the bundled versioned OS deps (``libnuma.so`` ->
``libnuma.so.1``, ...) inside ``torch/lib``. The bare name satisfies the
``dlopen``; the versioned file still satisfies ``NEEDED`` references. The wheel
version / filename is unchanged.

Scope: the **test** channel only (``whl/test/<rocm>``). By default it processes
release 2.13 for both ``rocm7.1`` and ``rocm7.2``.

This script:
  1. Discovers ``torch`` ROCm wheels for a version on the test channel index
     (e.g. https://download.pytorch.org/whl/test/rocm7.2/torch).
  2. Downloads each wheel.
  3. Adds the missing bare-name OS-dep aliases in ``torch/lib`` (RECORD is
     regenerated by auditwheel).
  4. Re-uploads under the SAME key to AWS S3 (``s3://pytorch/...``) and
     Cloudflare R2 (``s3://pytorch-downloads/...``), setting
     ``x-amz-meta-checksum-sha256`` on the object.

IMPORTANT: the wheel content changes but the filename does not, so the sha256
recorded in the PEP 503 index pages changes. Regenerate the index with
``s3_management/manage_v2.py`` after uploading, or ``pip --require-hashes``
installs will fail.

Environment variables:
  R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY
        Required to upload to Cloudflare R2. If missing, the R2 upload step is
        skipped with a warning.
  R2_BUCKET_NAME
        R2 bucket name (defaults to ``pytorch-downloads``).

AWS credentials for S3 are picked up from the standard boto3/AWS chain.

Usage:
  # local test-drive: repackage ONE local wheel, write it out, no upload
  python repackage_rocm_libnuma_fix.py \
      --wheel torch-2.13.0+rocm7.2-cp312-cp312-manylinux_2_28_x86_64.whl \
      --output-dir ./out
  # defaults: test channel, version 2.13.0, rocm7.1 + rocm7.2
  python repackage_rocm_libnuma_fix.py --dry-run
  python repackage_rocm_libnuma_fix.py
  # override version / limit to one rocm dir:
  python repackage_rocm_libnuma_fix.py --version 2.13.1 --rocm rocm7.2
"""

import argparse
import hashlib
import os
import re
import shutil
import sys
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path
from typing import List, Tuple


DEFAULT_PACKAGE = "torch"
CDN_BASE = "https://download.pytorch.org/whl"

S3_BUCKET = "pytorch"
R2_BUCKET_NAME_DEFAULT = "pytorch-downloads"

# Bundled OS deps that the old build_rocm.sh shipped under bare sonames and that
# get dlopen'd / linked by bare name at runtime. These are small, so we add a
# bare-name copy alongside the versioned file. rocSHMEM's NUMAWrapper needs
# ``libnuma.so`` specifically; the rest mirror build_rocm.sh for parity.
ALIAS_STEMS = {
    "libnuma",
    "libelf",
    "libtinfo",
    "libdw",
    "libdrm",
    "libdrm_amdgpu",
    "libgomp",
}


def discover_wheels(package: str, version: str, cpath: str) -> List[str]:
    """Return torch ROCm wheel filenames for ``version`` on the channel index.

    Filenames are returned decoded (``+`` not ``%2B``)."""
    index_url = f"{CDN_BASE}/{cpath}/{package}"
    print(f"+ Fetching index: {index_url}")
    with urllib.request.urlopen(index_url) as resp:
        html = resp.read().decode("utf-8", errors="replace")

    # Match the version segment with either +rocmX.Y or %2BrocmX.Y. The rocm
    # tag is the last path segment of cpath.
    rocm = cpath.rsplit("/", 1)[-1]
    pattern = re.compile(
        rf'href="[^"]*?/({re.escape(package)}-{re.escape(version)}'
        rf'(?:%2B|\+){re.escape(rocm)}-[^"#]+\.whl)'
    )
    found = {urllib.parse.unquote(m.group(1)) for m in pattern.finditer(html)}
    wheels = sorted(found)
    print(f"+ Found {len(wheels)} wheel(s) for {package}=={version}+{rocm}")
    return wheels


def download_wheel(filename: str, cpath: str, dest_dir: Path) -> Path:
    url = f"{CDN_BASE}/{cpath}/{urllib.parse.quote(filename)}"
    dest = dest_dir / filename
    print(f"+ Downloading {url}")
    with urllib.request.urlopen(url) as resp, open(dest, "wb") as out:
        shutil.copyfileobj(resp, out)
    return dest


def repackage_wheel(wheel_path: Path, output_dir: Path) -> Tuple[Path, List[str]]:
    """Add bare-name aliases for bundled versioned OS deps in ``torch/lib``.

    Uses auditwheel's ``InWheelCtx`` so RECORD is regenerated. The wheel name is
    unchanged. Returns (output_path, list_of_added_aliases)."""
    try:
        from auditwheel.wheeltools import InWheelCtx
    except ImportError:
        print(
            "Error: auditwheel package is not installed. "
            "Install it with 'pip install auditwheel'."
        )
        sys.exit(1)

    added: List[str] = []
    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_whl = Path(tmp_dir) / wheel_path.name
        with InWheelCtx(wheel_path) as ctx:
            ctx.out_wheel = tmp_whl

            torch_lib = Path(ctx.path) / "torch" / "lib"
            if not torch_lib.is_dir():
                raise RuntimeError(f"torch/lib not found in {wheel_path.name}")

            for so in sorted(torch_lib.iterdir()):
                if not so.is_file() or ".so." not in so.name:
                    continue
                stem = so.name.split(".so.", 1)[0]
                if stem not in ALIAS_STEMS:
                    continue
                bare_path = torch_lib / f"{stem}.so"
                if bare_path.exists() or bare_path.is_symlink():
                    continue
                # Symlink, not a copy: don't bundle any new binary content --
                # just alias the already-bundled versioned file so bare-name
                # dlopen/NEEDED lookups resolve. Restores build_rocm.sh
                # behavior (relative link, stays within torch/lib).
                bare_path.symlink_to(so.name)
                added.append(bare_path.name)

        if added:
            print(f"+ {wheel_path.name}: added bare aliases -> {', '.join(added)}")
        else:
            print(
                f"- {wheel_path.name}: nothing to alias "
                f"(already fixed, or no matching OS deps bundled)"
            )

        out_path = output_dir / wheel_path.name
        if not tmp_whl.exists():
            raise RuntimeError(
                f"auditwheel did not produce expected wheel at {tmp_whl}"
            )
        shutil.move(str(tmp_whl), out_path)
    return out_path, added


def sha256_of(file_path: Path) -> str:
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def upload_to_s3(
    file_path: Path, bucket: str, key: str, sha256: str, dry_run: bool
) -> None:
    if dry_run:
        print(
            f"+ DRY RUN: would upload {file_path.name} to "
            f"s3://{bucket}/{key} (sha256={sha256})"
        )
        return

    import boto3  # type: ignore[import]

    client = boto3.client("s3")
    print(f"+ Uploading to s3://{bucket}/{key}")
    client.upload_file(
        Filename=str(file_path),
        Bucket=bucket,
        Key=key,
        ExtraArgs={
            "ACL": "public-read",
            "Metadata": {"checksum-sha256": sha256},
        },
    )


def upload_to_r2(
    file_path: Path, bucket: str, key: str, sha256: str, dry_run: bool
) -> None:
    account_id = os.environ.get("R2_ACCOUNT_ID", "")
    access_key = os.environ.get("R2_ACCESS_KEY_ID", "")
    secret_key = os.environ.get("R2_SECRET_ACCESS_KEY", "")
    if not (account_id and access_key and secret_key):
        print(
            "- WARNING: R2 credentials not configured "
            "(R2_ACCOUNT_ID / R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY); "
            "skipping R2 upload"
        )
        return

    if dry_run:
        print(
            f"+ DRY RUN: would upload {file_path.name} to "
            f"R2 s3://{bucket}/{key} (sha256={sha256})"
        )
        return

    import boto3  # type: ignore[import]

    endpoint_url = f"https://{account_id}.r2.cloudflarestorage.com"
    client = boto3.client(
        "s3",
        endpoint_url=endpoint_url,
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name="auto",
    )
    print(f"+ Uploading to R2 s3://{bucket}/{key}")
    client.upload_file(
        Filename=str(file_path),
        Bucket=bucket,
        Key=key,
        ExtraArgs={"Metadata": {"checksum-sha256": sha256}},
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--package", default=DEFAULT_PACKAGE, help="Package name")
    parser.add_argument(
        "--version",
        default="2.13.0",
        help="Package version (default: 2.13.0)",
    )
    parser.add_argument(
        "--rocm",
        nargs="+",
        default=["rocm7.1", "rocm7.2"],
        help="ROCm channel dir(s) under whl/test/ (default: rocm7.1 rocm7.2)",
    )
    parser.add_argument(
        "--wheel",
        type=Path,
        default=None,
        help="Repackage a single wheel (e.g. a rocm7.2 cp312 wheel). May be a "
        "local .whl path, OR just a wheel filename -- if it isn't a local file "
        "it is downloaded from whl/test/<rocm> (rocm inferred from the name).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Write repackaged wheel(s) here and SKIP upload (local test-drive). "
        "The output is kept.",
    )
    parser.add_argument(
        "--work-dir",
        type=Path,
        default=None,
        help="Base dir for the temp download/unpack scratch (also used as "
        "TMPDIR for auditwheel). Point at a large filesystem; ROCm wheels are "
        "~6GB each and peak usage is a few wheels' worth. Default: system temp.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Do everything except the actual S3/R2 uploads",
    )
    parser.add_argument(
        "--r2-bucket",
        default=os.environ.get("R2_BUCKET_NAME", R2_BUCKET_NAME_DEFAULT),
        help="R2 bucket name",
    )
    return parser.parse_args()


def verify_repackaged(wheel_path: Path, added: List[str]) -> bool:
    """Check the repackaged wheel actually contains each added alias and lists
    it in RECORD (so metadata is consistent). Returns True on success."""
    import zipfile

    with zipfile.ZipFile(wheel_path) as zf:
        names = set(zf.namelist())
        record_name = next(
            (n for n in names if n.endswith(".dist-info/RECORD")), None
        )
        record = zf.read(record_name).decode("utf-8", "replace") if record_name else ""

    ok = True
    for alias in added:
        in_wheel = any(n.endswith(f"torch/lib/{alias}") for n in names)
        in_record = f"torch/lib/{alias}," in record
        status = "PASS" if (in_wheel and in_record) else "FAIL"
        print(f"  verify {alias}: in_wheel={in_wheel} in_RECORD={in_record} -> {status}")
        ok = ok and in_wheel and in_record
    return ok


def process_one(
    local_wheel: Path,
    cpath: str,
    output_dir: Path,
    args: argparse.Namespace,
    local_only: bool,
) -> bool:
    """Repackage one wheel and upload (unless local_only). Returns True if the
    wheel was changed. Cleans up the repackaged output after upload so only one
    wheel's worth of scratch is on disk at a time."""
    repackaged, added = repackage_wheel(local_wheel, output_dir)
    if not added:
        print(f"+ {repackaged.name}: nothing changed, skipping")
        if not local_only:
            repackaged.unlink(missing_ok=True)
        return False

    verify_repackaged(repackaged, added)

    if local_only:
        print(f"+ Wrote repackaged wheel (no upload): {repackaged}")
        return True

    sha256 = sha256_of(repackaged)
    print(f"+ sha256({repackaged.name}) = {sha256}")
    key = f"whl/{cpath}/{repackaged.name}"
    upload_to_s3(repackaged, S3_BUCKET, key, sha256, args.dry_run)
    upload_to_r2(repackaged, args.r2_bucket, key, sha256, args.dry_run)
    repackaged.unlink(missing_ok=True)  # free space before the next wheel
    return True


def main() -> int:
    args = parse_args()
    local_only = args.output_dir is not None

    base_tmp = None
    if args.work_dir is not None:
        base = args.work_dir.expanduser().resolve()
        base.mkdir(parents=True, exist_ok=True)
        # Route ALL scratch here, not /tmp: our own mkdtemp (via base_tmp) AND
        # auditwheel's internal InTemporaryDirectory (wheel unpack). Setting
        # tempfile.tempdir directly -- not just $TMPDIR -- guarantees it takes
        # effect even if gettempdir() was already cached elsewhere.
        os.environ["TMPDIR"] = str(base)
        tempfile.tempdir = str(base)
        base_tmp = str(base)

    work_dir = Path(tempfile.mkdtemp(prefix="repackage-rocm-libnuma-", dir=base_tmp))

    # Pre-flight: each ROCm wheel needs ~download + unpack + output on this
    # filesystem. Fail fast (with guidance) instead of dying mid-unpack.
    min_free_gb = 25
    free_gb = shutil.disk_usage(work_dir).free / 1e9
    print(f"+ Scratch: {work_dir}  ({free_gb:.1f} GB free)")
    if free_gb < min_free_gb:
        print(
            f"- ERROR: only {free_gb:.1f} GB free where scratch lives; each "
            f"ROCm wheel needs ~{min_free_gb} GB (download + auditwheel unpack "
            f"+ output). Re-run with --work-dir pointing at a larger filesystem "
            f"(check `df -h`)."
        )
        shutil.rmtree(work_dir, ignore_errors=True)
        return 1

    download_dir = work_dir / "download"
    download_dir.mkdir(exist_ok=True)
    if local_only:
        output_dir = args.output_dir.expanduser().resolve()
        output_dir.mkdir(parents=True, exist_ok=True)
    else:
        output_dir = work_dir / "repackaged"
        output_dir.mkdir(exist_ok=True)
    print(f"+ Working directory: {work_dir}")

    try:
        total_found = 0
        total_done = 0

        if args.wheel is not None:
            wp = args.wheel.expanduser()
            m = re.search(r"[+%](?:2B)?(rocm[0-9.]+)", wp.name)
            rocm = m.group(1) if m else (args.rocm[0] if args.rocm else "rocm7.2")
            cpath = f"test/{rocm}"
            keep_input = wp.is_file()
            if keep_input:
                local = wp.resolve()
                print(f"+ Single-wheel mode (local file): {local.name} (rocm={rocm})")
            else:
                print(
                    f"+ Single-wheel mode: {wp.name} not found locally, "
                    f"downloading from whl/{cpath}"
                )
                local = download_wheel(wp.name, cpath, download_dir)
            total_found = 1
            try:
                if process_one(local, cpath, output_dir, args, local_only):
                    total_done += 1
            finally:
                if not keep_input:
                    local.unlink(missing_ok=True)
        else:
            for rocm in args.rocm:
                cpath = f"test/{rocm}"  # test channel only: whl/test/<rocm>
                print(f"\n=== {args.package}=={args.version} on whl/{cpath} ===")
                wheels = discover_wheels(args.package, args.version, cpath)
                total_found += len(wheels)
                if not wheels:
                    print(f"- No wheels for {args.package}=={args.version} ({cpath})")
                    continue
                # Process one wheel at a time: download -> repackage -> upload ->
                # delete, so peak disk usage stays at ~one wheel, not all of them.
                for wheel_filename in wheels:
                    downloaded = download_wheel(wheel_filename, cpath, download_dir)
                    try:
                        if process_one(downloaded, cpath, output_dir, args, local_only):
                            total_done += 1
                    finally:
                        downloaded.unlink(missing_ok=True)

        verb = "wrote" if local_only else "repackaged/uploaded"
        print(f"\n+ Done. {verb} {total_done}/{total_found} wheel(s).")
        if not local_only:
            print(
                "+ Reminder: repackaged wheels keep the same filename but have "
                "new content/sha256. Regenerate the PEP 503 index (and #sha256= "
                "fragments) via s3_management/manage_v2.py after uploads."
            )
        return 0
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
