#!/usr/bin/env python3
"""
Repackage torchaudio cu130 wheels as cu132 wheels.

This script:
  1. Discovers all torchaudio wheels of a given version under
     https://download.pytorch.org/whl/test/cu130/torchaudio
  2. Downloads each wheel.
  3. Rewrites the wheel local-version label from ``+cu130`` to ``+cu132``
     (METADATA ``Version:`` field, ``.dist-info`` directory name, and the
     wheel filename). The RECORD file is regenerated by auditwheel.
  4. Uploads each repackaged wheel to:
       - AWS S3:  s3://pytorch/whl/test/cu132/
       - Cloudflare R2: s3://pytorch-downloads/whl/test/cu132/
     Each upload sets ``x-amz-meta-checksum-sha256`` on the object so the
     PEP 503 index pages can pick it up.

Environment variables:
  R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY
        Required to upload to Cloudflare R2. If missing, the R2 upload step
        is skipped with a warning.
  R2_BUCKET_NAME
        R2 bucket name (defaults to ``pytorch-downloads``).

AWS credentials for S3 are picked up from the standard boto3/AWS chain.

Usage:
  python repackage_torchaudio_cu130_to_cu132.py --version 2.11.0
  python repackage_torchaudio_cu130_to_cu132.py --version 2.11.0 --dry-run
  python repackage_torchaudio_cu130_to_cu132.py --version 2.11.0 \
      --skip-s3            # only upload to R2
  python repackage_torchaudio_cu130_to_cu132.py --version 2.11.0 \
      --skip-r2            # only upload to S3
"""

import argparse
import hashlib
import os
import re
import shutil
import sys
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path
from typing import List, Optional

DEFAULT_PACKAGE = "torchaudio"
DEFAULT_VERSION = "2.11.0"
SOURCE_CUDA = "cu130"
TARGET_CUDA = "cu132"

INDEX_URL = (
    "https://download.pytorch.org/whl/test/{cuda}/{package}"
)
DOWNLOAD_BASE = "https://download.pytorch.org/whl/test/{cuda}/{filename}"

S3_BUCKET = "pytorch"
S3_PREFIX = "whl/test/{cuda}"

R2_BUCKET_NAME_DEFAULT = "pytorch-downloads"
R2_PREFIX = "whl/test/{cuda}"


def discover_wheels(package: str, version: str, cuda: str) -> List[str]:
    """Return list of wheel filenames for ``package`` at ``version`` on the
    cu<NN> test channel index. Filenames are returned with ``+`` (not URL
    encoded)."""
    index_url = INDEX_URL.format(cuda=cuda, package=package)
    print(f"+ Fetching index: {index_url}")
    with urllib.request.urlopen(index_url) as resp:
        html = resp.read().decode("utf-8", errors="replace")

    # Match either +cu130 or %2Bcu130 in the version segment of the filename.
    pattern = re.compile(
        rf'href="[^"]*?/({re.escape(package)}-{re.escape(version)}'
        rf'(?:%2B|\+){re.escape(cuda)}-[^"#]+\.whl)'
    )
    found = set()
    for match in pattern.finditer(html):
        filename = urllib.parse.unquote(match.group(1))
        found.add(filename)
    wheels = sorted(found)
    print(f"+ Found {len(wheels)} wheel(s) for {package}=={version}+{cuda}")
    return wheels


def download_wheel(filename: str, cuda: str, dest_dir: Path) -> Path:
    """Download ``filename`` from the test cu<NN> channel into ``dest_dir``."""
    url = DOWNLOAD_BASE.format(
        cuda=cuda, filename=urllib.parse.quote(filename)
    )
    dest = dest_dir / filename
    print(f"+ Downloading {url}")
    with urllib.request.urlopen(url) as resp, open(dest, "wb") as out:
        shutil.copyfileobj(resp, out)
    return dest


def repackage_wheel(
    wheel_path: Path,
    output_dir: Path,
    source_cuda: str,
    target_cuda: str,
) -> Path:
    """Rewrite the ``+source_cuda`` local-version label to ``+target_cuda``
    inside ``wheel_path`` and write the new wheel into ``output_dir``.

    Uses auditwheel's ``InWheelCtx`` so the RECORD file is regenerated."""
    try:
        from auditwheel.wheeltools import InWheelCtx
    except ImportError:
        print(
            "Error: auditwheel package is not installed. "
            "Install it with 'pip install auditwheel'."
        )
        sys.exit(1)

    old_label = f"+{source_cuda}"
    new_label = f"+{target_cuda}"

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_whl = os.path.join(tmp_dir, wheel_path.name)
        with InWheelCtx(str(wheel_path)) as ctx:
            ctx.out_wheel = tmp_whl

            dist_info_dirs = [
                d
                for d in os.listdir(ctx.path)
                if d.endswith(".dist-info")
                and os.path.isdir(os.path.join(ctx.path, d))
            ]
            if not dist_info_dirs:
                raise RuntimeError(
                    f"No .dist-info directory found in {wheel_path}"
                )
            dist_info_dir = dist_info_dirs[0]

            metadata_file = os.path.join(
                ctx.path, dist_info_dir, "METADATA"
            )
            if not os.path.exists(metadata_file):
                raise RuntimeError(
                    f"METADATA file not found in {wheel_path}"
                )

            old_version: Optional[str] = None
            with open(metadata_file, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith("Version:"):
                        old_version = line.split(":", 1)[1].strip()
                        break
            if not old_version:
                raise RuntimeError(
                    f"Could not find Version in {metadata_file}"
                )
            if old_label not in old_version:
                raise RuntimeError(
                    f"Version {old_version!r} does not contain {old_label!r}"
                )

            new_version = old_version.replace(old_label, new_label)
            print(
                f"+ Rewriting version: {old_version} -> {new_version} "
                f"({wheel_path.name})"
            )

            # Update every text file under .dist-info that mentions the
            # old version string. RECORD will be regenerated on context
            # exit, so its hashes will be correct.
            for root, _dirs, files in os.walk(
                os.path.join(ctx.path, dist_info_dir)
            ):
                for name in files:
                    file_path = os.path.join(root, name)
                    try:
                        with open(
                            file_path,
                            "r",
                            encoding="utf-8",
                            errors="ignore",
                        ) as f:
                            content = f.read()
                    except OSError:
                        continue
                    updated = content.replace(old_version, new_version)
                    if updated != content:
                        with open(file_path, "w", encoding="utf-8") as f:
                            f.write(updated)

            new_dist_info_dir = dist_info_dir.replace(
                old_version, new_version
            )
            if new_dist_info_dir != dist_info_dir:
                os.rename(
                    os.path.join(ctx.path, dist_info_dir),
                    os.path.join(ctx.path, new_dist_info_dir),
                )

        new_filename = wheel_path.name.replace(old_label, new_label)
        out_path = output_dir / new_filename
        if not os.path.exists(tmp_whl):
            raise RuntimeError(
                f"auditwheel did not produce expected wheel at {tmp_whl}"
            )
        shutil.move(tmp_whl, out_path)
        print(f"+ Repackaged wheel: {out_path}")
        return out_path


def sha256_of(file_path: Path) -> str:
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def upload_to_s3(
    file_path: Path,
    bucket: str,
    key: str,
    sha256: str,
    dry_run: bool,
) -> None:
    if dry_run:
        print(
            f"+ DRY RUN: would upload {file_path.name} to "
            f"s3://{bucket}/{key} (sha256={sha256})"
        )
        return

    import boto3  # type: ignore[import]

    client = boto3.client("s3")
    print(f"+ Uploading to s3://{bucket}/{key}")
    client.upload_file(
        Filename=str(file_path),
        Bucket=bucket,
        Key=key,
        ExtraArgs={
            "ACL": "public-read",
            "Metadata": {"checksum-sha256": sha256},
        },
    )


def upload_to_r2(
    file_path: Path,
    bucket: str,
    key: str,
    sha256: str,
    dry_run: bool,
) -> None:
    account_id = os.environ.get("R2_ACCOUNT_ID", "")
    access_key = os.environ.get("R2_ACCESS_KEY_ID", "")
    secret_key = os.environ.get("R2_SECRET_ACCESS_KEY", "")
    if not (account_id and access_key and secret_key):
        print(
            "- WARNING: R2 credentials not configured "
            "(R2_ACCOUNT_ID / R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY); "
            "skipping R2 upload"
        )
        return

    if dry_run:
        print(
            f"+ DRY RUN: would upload {file_path.name} to "
            f"R2 s3://{bucket}/{key} (sha256={sha256})"
        )
        return

    import boto3  # type: ignore[import]

    endpoint_url = f"https://{account_id}.r2.cloudflarestorage.com"
    client = boto3.client(
        "s3",
        endpoint_url=endpoint_url,
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name="auto",
    )
    print(f"+ Uploading to R2 s3://{bucket}/{key}")
    client.upload_file(
        Filename=str(file_path),
        Bucket=bucket,
        Key=key,
        ExtraArgs={"Metadata": {"checksum-sha256": sha256}},
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--package", default=DEFAULT_PACKAGE, help="Package name"
    )
    parser.add_argument(
        "--version", default=DEFAULT_VERSION, help="Package version (e.g. 2.11.0)"
    )
    parser.add_argument(
        "--source-cuda", default=SOURCE_CUDA, help="Source CUDA tag (e.g. cu130)"
    )
    parser.add_argument(
        "--target-cuda", default=TARGET_CUDA, help="Target CUDA tag (e.g. cu132)"
    )
    parser.add_argument(
        "--work-dir",
        default=None,
        help="Working directory for downloads and repackaged wheels "
        "(default: a fresh temp dir that is removed on exit)",
    )
    parser.add_argument(
        "--keep-work-dir",
        action="store_true",
        help="Keep the working directory after the script exits",
    )
    parser.add_argument(
        "--skip-s3", action="store_true", help="Skip the AWS S3 upload"
    )
    parser.add_argument(
        "--skip-r2", action="store_true", help="Skip the Cloudflare R2 upload"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Do everything except the actual S3/R2 uploads",
    )
    parser.add_argument(
        "--r2-bucket",
        default=os.environ.get("R2_BUCKET_NAME", R2_BUCKET_NAME_DEFAULT),
        help="R2 bucket name",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if args.work_dir:
        work_dir = Path(args.work_dir).resolve()
        work_dir.mkdir(parents=True, exist_ok=True)
        cleanup = False
    else:
        work_dir = Path(tempfile.mkdtemp(prefix="repackage-cu-"))
        cleanup = not args.keep_work_dir

    download_dir = work_dir / "download"
    output_dir = work_dir / "repackaged"
    download_dir.mkdir(exist_ok=True)
    output_dir.mkdir(exist_ok=True)

    print(f"+ Working directory: {work_dir}")

    try:
        wheels = discover_wheels(
            args.package, args.version, args.source_cuda
        )
        if not wheels:
            print(
                f"- No wheels found for {args.package}=={args.version} "
                f"on {args.source_cuda}"
            )
            return 1

        s3_prefix = S3_PREFIX.format(cuda=args.target_cuda)
        r2_prefix = R2_PREFIX.format(cuda=args.target_cuda)

        for wheel_filename in wheels:
            downloaded = download_wheel(
                wheel_filename, args.source_cuda, download_dir
            )
            repackaged = repackage_wheel(
                downloaded,
                output_dir,
                args.source_cuda,
                args.target_cuda,
            )
            sha256 = sha256_of(repackaged)
            print(f"+ sha256({repackaged.name}) = {sha256}")

            s3_key = f"{s3_prefix}/{repackaged.name}"
            r2_key = f"{r2_prefix}/{repackaged.name}"

            if not args.skip_s3:
                upload_to_s3(
                    repackaged, S3_BUCKET, s3_key, sha256, args.dry_run
                )
            else:
                print("+ --skip-s3 set, skipping S3 upload")

            if not args.skip_r2:
                upload_to_r2(
                    repackaged, args.r2_bucket, r2_key, sha256, args.dry_run
                )
            else:
                print("+ --skip-r2 set, skipping R2 upload")

        print(f"+ Done. Processed {len(wheels)} wheel(s).")
        print(
            "+ Reminder: regenerate the PEP 503 index for "
            f"whl/test/{args.target_cuda} via "
            "s3_management/manage_v2.py once uploads are complete."
        )
        return 0
    finally:
        if cleanup:
            shutil.rmtree(work_dir, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
