#!/usr/bin/env python3
"""
Repackage torchaudio cu130 wheels as cu132 wheels.

This script:
  1. Discovers all torchaudio wheels of a given version under
     https://download.pytorch.org/whl/test/cu130/torchaudio
  2. Downloads each wheel.
  3. Rewrites the wheel local-version label from ``+cu130`` to ``+cu132``
     (METADATA ``Version:`` field, ``.dist-info`` directory name, and the
     wheel filename). The RECORD file is regenerated by auditwheel.
  4. Removes the ``_check_cuda_version()`` runtime guard from
     ``torchaudio/_extension/__init__.py`` inside the wheel. torchaudio is
     now built against the PyTorch stable C++ ABI, so the strict CUDA
     version match is no longer required and would otherwise fail when a
     cu132-tagged torchaudio wheel runs alongside a torch built for a
     different CUDA minor version. The function definition in ``utils.py``
     is preserved so external callers (e.g. the pytorch/builder smoke
     test) keep working.
  5. Uploads each repackaged wheel to:
       - AWS S3:  s3://pytorch/whl/test/cu132/
       - Cloudflare R2: s3://pytorch-downloads/whl/test/cu132/
     Each upload sets ``x-amz-meta-checksum-sha256`` on the object so the
     PEP 503 index pages can pick it up.

Environment variables:
  R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY
        Required to upload to Cloudflare R2. If missing, the R2 upload step
        is skipped with a warning.
  R2_BUCKET_NAME
        R2 bucket name (defaults to ``pytorch-downloads``).

AWS credentials for S3 are picked up from the standard boto3/AWS chain.

Usage:
  python repackage_torchaudio_cu130_to_cu132.py --version 2.11.0
  python repackage_torchaudio_cu130_to_cu132.py --version 2.11.0 --dry-run
"""

import argparse
import hashlib
import os
import re
import shutil
import sys
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path
from typing import List, Optional


DEFAULT_PACKAGE = "torchaudio"
DEFAULT_VERSION = "2.11.0"
SOURCE_CUDA = "cu130"
TARGET_CUDA = "cu132"

INDEX_URL = "https://download.pytorch.org/whl/test/{cuda}/{package}"
DOWNLOAD_BASE = "https://download.pytorch.org/whl/test/{cuda}/{filename}"

S3_BUCKET = "pytorch"
S3_PREFIX = "whl/test/{cuda}"

R2_BUCKET_NAME_DEFAULT = "pytorch-downloads"
R2_PREFIX = "whl/test/{cuda}"

EXTENSION_INIT_PATH = "torchaudio/_extension/__init__.py"
EXTENSION_UTILS_PATH = "torchaudio/_extension/utils.py"
CHECK_CUDA_CALL_RE = re.compile(r"^[ \t]*_check_cuda_version\(\)[ \t]*\n", re.MULTILINE)
# Match the `if ta_version != t_version: raise RuntimeError(...)` block inside
# _check_cuda_version() in utils.py. The raise spans multiple lines, so we
# match the whole if-body by indent.
CHECK_CUDA_RAISE_RE = re.compile(
    r"^(?P<indent>[ \t]+)if ta_version != t_version:[ \t]*\n"
    r"(?:(?P=indent)[ \t]+.*\n)+",
    re.MULTILINE,
)


def discover_wheels(package: str, version: str, cuda: str) -> List[str]:
    """Return list of wheel filenames for ``package`` at ``version`` on the
    cu<NN> test channel index. Filenames are returned with ``+`` (not URL
    encoded)."""
    index_url = INDEX_URL.format(cuda=cuda, package=package)
    print(f"+ Fetching index: {index_url}")
    with urllib.request.urlopen(index_url) as resp:
        html = resp.read().decode("utf-8", errors="replace")

    # Match either +cu130 or %2Bcu130 in the version segment of the filename.
    pattern = re.compile(
        rf'href="[^"]*?/({re.escape(package)}-{re.escape(version)}'
        rf'(?:%2B|\+){re.escape(cuda)}-[^"#]+\.whl)'
    )
    found = set()
    for match in pattern.finditer(html):
        filename = urllib.parse.unquote(match.group(1))
        found.add(filename)
    wheels = sorted(found)
    print(f"+ Found {len(wheels)} wheel(s) for {package}=={version}+{cuda}")
    return wheels


def download_wheel(filename: str, cuda: str, dest_dir: Path) -> Path:
    """Download ``filename`` from the test cu<NN> channel into ``dest_dir``."""
    url = DOWNLOAD_BASE.format(cuda=cuda, filename=urllib.parse.quote(filename))
    dest = dest_dir / filename
    print(f"+ Downloading {url}")
    with urllib.request.urlopen(url) as resp, open(dest, "wb") as out:
        shutil.copyfileobj(resp, out)
    return dest


def repackage_wheel(
    wheel_path: Path,
    output_dir: Path,
    source_cuda: str,
    target_cuda: str,
) -> Path:
    """Rewrite the ``+source_cuda`` local-version label to ``+target_cuda``
    inside ``wheel_path`` and write the new wheel into ``output_dir``.

    Uses auditwheel's ``InWheelCtx`` so the RECORD file is regenerated."""
    try:
        from auditwheel.wheeltools import InWheelCtx
    except ImportError:
        print(
            "Error: auditwheel package is not installed. "
            "Install it with 'pip install auditwheel'."
        )
        sys.exit(1)

    old_label = f"+{source_cuda}"
    new_label = f"+{target_cuda}"

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_whl = Path(tmp_dir) / wheel_path.name
        with InWheelCtx(wheel_path) as ctx:
            ctx.out_wheel = tmp_whl

            dist_info_dirs = [
                d
                for d in os.listdir(ctx.path)
                if d.endswith(".dist-info") and os.path.isdir(os.path.join(ctx.path, d))
            ]
            if not dist_info_dirs:
                raise RuntimeError(f"No .dist-info directory found in {wheel_path}")
            dist_info_dir = dist_info_dirs[0]

            metadata_file = os.path.join(ctx.path, dist_info_dir, "METADATA")
            if not os.path.exists(metadata_file):
                raise RuntimeError(f"METADATA file not found in {wheel_path}")

            old_version: Optional[str] = None
            with open(metadata_file, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith("Version:"):
                        old_version = line.split(":", 1)[1].strip()
                        break
            if not old_version:
                raise RuntimeError(f"Could not find Version in {metadata_file}")
            if old_label not in old_version:
                raise RuntimeError(
                    f"Version {old_version!r} does not contain {old_label!r}"
                )

            new_version = old_version.replace(old_label, new_label)
            print(
                f"+ Rewriting version: {old_version} -> {new_version} "
                f"({wheel_path.name})"
            )

            # Update every text file under .dist-info that mentions the
            # old version string. RECORD will be regenerated on context
            # exit, so its hashes will be correct.
            for root, _dirs, files in os.walk(os.path.join(ctx.path, dist_info_dir)):
                for name in files:
                    file_path = os.path.join(root, name)
                    try:
                        with open(
                            file_path,
                            "r",
                            encoding="utf-8",
                            errors="ignore",
                        ) as f:
                            content = f.read()
                    except OSError:
                        continue
                    updated = content.replace(old_version, new_version)
                    if updated != content:
                        with open(file_path, "w", encoding="utf-8") as f:
                            f.write(updated)

            new_dist_info_dir = dist_info_dir.replace(old_version, new_version)
            if new_dist_info_dir != dist_info_dir:
                os.rename(
                    os.path.join(ctx.path, dist_info_dir),
                    os.path.join(ctx.path, new_dist_info_dir),
                )

            # torchaudio is now built against the PyTorch stable C++ ABI,
            # so the runtime _check_cuda_version() guard is no longer needed
            # and would otherwise fail on cross-CUDA-version installs (e.g.
            # a torchaudio cu132 wheel running against torch built for a
            # different CUDA minor). Two patches are required:
            #   (a) strip the call site in __init__.py so importing the
            #       package does not raise, and
            #   (b) neutralize the version-mismatch raise in utils.py so
            #       external callers (e.g. the pytorch smoke test, which
            #       calls torchaudio._extension._check_cuda_version()
            #       directly) do not raise either.
            init_file = os.path.join(ctx.path, EXTENSION_INIT_PATH)
            if not os.path.exists(init_file):
                raise RuntimeError(f"{EXTENSION_INIT_PATH} not found in {wheel_path}")
            with open(init_file, "r", encoding="utf-8") as f:
                init_src = f.read()
            patched_src, count = CHECK_CUDA_CALL_RE.subn("", init_src)
            if count == 0:
                raise RuntimeError(
                    f"No _check_cuda_version() call found in "
                    f"{EXTENSION_INIT_PATH} of {wheel_path.name}"
                )
            if count > 1:
                print(
                    f"- WARNING: removed {count} _check_cuda_version() "
                    f"calls from {wheel_path.name} (expected 1)"
                )
            with open(init_file, "w", encoding="utf-8") as f:
                f.write(patched_src)
            print(
                f"+ Removed _check_cuda_version() call from "
                f"{EXTENSION_INIT_PATH} ({wheel_path.name})"
            )

            utils_file = os.path.join(ctx.path, EXTENSION_UTILS_PATH)
            if not os.path.exists(utils_file):
                raise RuntimeError(f"{EXTENSION_UTILS_PATH} not found in {wheel_path}")
            with open(utils_file, "r", encoding="utf-8") as f:
                utils_src = f.read()
            patched_utils, utils_count = CHECK_CUDA_RAISE_RE.subn(
                lambda m: (
                    f"{m.group('indent')}pass  "
                    f"# CUDA version mismatch check disabled by "
                    f"repackage_torchaudio_cu130_to_cu132.py\n"
                ),
                utils_src,
            )
            if utils_count == 0:
                raise RuntimeError(
                    f"No `if ta_version != t_version:` block found in "
                    f"{EXTENSION_UTILS_PATH} of {wheel_path.name}"
                )
            if utils_count > 1:
                print(
                    f"- WARNING: replaced {utils_count} CUDA-mismatch "
                    f"raise blocks in {wheel_path.name} (expected 1)"
                )
            with open(utils_file, "w", encoding="utf-8") as f:
                f.write(patched_utils)
            print(
                f"+ Disabled CUDA version mismatch raise in "
                f"{EXTENSION_UTILS_PATH} ({wheel_path.name})"
            )

        new_filename = wheel_path.name.replace(old_label, new_label)
        out_path = output_dir / new_filename
        if not tmp_whl.exists():
            raise RuntimeError(
                f"auditwheel did not produce expected wheel at {tmp_whl}"
            )
        shutil.move(str(tmp_whl), out_path)
        print(f"+ Repackaged wheel: {out_path}")
        return out_path


def sha256_of(file_path: Path) -> str:
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def upload_to_s3(
    file_path: Path,
    bucket: str,
    key: str,
    sha256: str,
    dry_run: bool,
) -> None:
    if dry_run:
        print(
            f"+ DRY RUN: would upload {file_path.name} to "
            f"s3://{bucket}/{key} (sha256={sha256})"
        )
        return

    import boto3  # type: ignore[import]

    client = boto3.client("s3")
    print(f"+ Uploading to s3://{bucket}/{key}")
    client.upload_file(
        Filename=str(file_path),
        Bucket=bucket,
        Key=key,
        ExtraArgs={
            "ACL": "public-read",
            "Metadata": {"checksum-sha256": sha256},
        },
    )


def upload_to_r2(
    file_path: Path,
    bucket: str,
    key: str,
    sha256: str,
    dry_run: bool,
) -> None:
    account_id = os.environ.get("R2_ACCOUNT_ID", "")
    access_key = os.environ.get("R2_ACCESS_KEY_ID", "")
    secret_key = os.environ.get("R2_SECRET_ACCESS_KEY", "")
    if not (account_id and access_key and secret_key):
        print(
            "- WARNING: R2 credentials not configured "
            "(R2_ACCOUNT_ID / R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY); "
            "skipping R2 upload"
        )
        return

    if dry_run:
        print(
            f"+ DRY RUN: would upload {file_path.name} to "
            f"R2 s3://{bucket}/{key} (sha256={sha256})"
        )
        return

    import boto3  # type: ignore[import]

    endpoint_url = f"https://{account_id}.r2.cloudflarestorage.com"
    client = boto3.client(
        "s3",
        endpoint_url=endpoint_url,
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name="auto",
    )
    print(f"+ Uploading to R2 s3://{bucket}/{key}")
    client.upload_file(
        Filename=str(file_path),
        Bucket=bucket,
        Key=key,
        ExtraArgs={"Metadata": {"checksum-sha256": sha256}},
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--package", default=DEFAULT_PACKAGE, help="Package name")
    parser.add_argument(
        "--version", default=DEFAULT_VERSION, help="Package version (e.g. 2.11.0)"
    )
    parser.add_argument(
        "--source-cuda", default=SOURCE_CUDA, help="Source CUDA tag (e.g. cu130)"
    )
    parser.add_argument(
        "--target-cuda", default=TARGET_CUDA, help="Target CUDA tag (e.g. cu132)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Do everything except the actual S3/R2 uploads",
    )
    parser.add_argument(
        "--r2-bucket",
        default=os.environ.get("R2_BUCKET_NAME", R2_BUCKET_NAME_DEFAULT),
        help="R2 bucket name",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    work_dir = Path(tempfile.mkdtemp(prefix="repackage-cu-"))
    download_dir = work_dir / "download"
    output_dir = work_dir / "repackaged"
    download_dir.mkdir(exist_ok=True)
    output_dir.mkdir(exist_ok=True)

    print(f"+ Working directory: {work_dir}")

    try:
        wheels = discover_wheels(args.package, args.version, args.source_cuda)
        if not wheels:
            print(
                f"- No wheels found for {args.package}=={args.version} "
                f"on {args.source_cuda}"
            )
            return 1

        s3_prefix = S3_PREFIX.format(cuda=args.target_cuda)
        r2_prefix = R2_PREFIX.format(cuda=args.target_cuda)

        for wheel_filename in wheels:
            downloaded = download_wheel(wheel_filename, args.source_cuda, download_dir)
            repackaged = repackage_wheel(
                downloaded,
                output_dir,
                args.source_cuda,
                args.target_cuda,
            )
            sha256 = sha256_of(repackaged)
            print(f"+ sha256({repackaged.name}) = {sha256}")

            s3_key = f"{s3_prefix}/{repackaged.name}"
            r2_key = f"{r2_prefix}/{repackaged.name}"

            upload_to_s3(repackaged, S3_BUCKET, s3_key, sha256, args.dry_run)
            upload_to_r2(repackaged, args.r2_bucket, r2_key, sha256, args.dry_run)

        print(f"+ Done. Processed {len(wheels)} wheel(s).")
        print(
            "+ Reminder: regenerate the PEP 503 index for "
            f"whl/test/{args.target_cuda} via "
            "s3_management/manage_v2.py once uploads are complete."
        )
        return 0
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
