[tools]
python = "3.13"
uv = "latest"
"aqua:casey/just" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:tamasfe/taplo" = "latest"
"npm:markdownlint-cli2" = "latest"
node = "latest"

[env]
PROJECT_NAME = "greenlight"
VIRTUAL_ENV = "{{config_root}}/.venv"
_.path = ["{{config_root}}/.venv/bin"]

[settings]
auto_install = true
