{
 "title": "Framework Health",
 "description": "Metrics on binary size, sccache, resident memory, etc.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "build_environment",
    "label": "Build Environment",
    "query": "select build_environment from sccache_stats where $__timeFilter(updated_at) group by build_environment;"
   }
  ]
 },
 "panels": [
  {
   "title": "Binary Size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT updated_at as \"time\",\n       library,\n       (SIZE / 1024 / 1024) AS \"MB\"\nFROM binary_size\nWHERE branch = \"master\"\n  AND build_environment = \"$build_environment\"\n  AND library like \"libtorch%\"\n  AND $__timeFilter(updated_at);"
    }
   ]
  },
  {
   "title": "Peak Memory Size (MB)",
   "type": "timeseries",
   "description": "memory usage of `import torch` vs `import sys`",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT updated_at as \"time\",\n       test_name,\n       (peak_memory_bytes / 1024 / 1024) as \"Maximum RSS (MB)\"\nFROM import_stats\nWHERE branch = \"master\"\n  AND build_environment = \"$build_environment-default\"\n  AND $__timeFilter(updated_at);\n  \n"
    }
   ]
  },
  {
   "title": "sccache stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT updated_at AS \"time\",\n       cache_hits,\n       cache_misses,\n       compile_requests\nFROM sccache_stats\nWHERE branch = \"master\"\n  AND build_environment=\"$build_environment\"\n  AND $__timeFilter(updated_at)\nORDER BY updated_at DESC;"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "table",
   "description": "Note: This might not be the actual commit since stacked commits only show the top one",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT convert_tz(head_commit_timestamp, 'US/Pacific', 'GMT') AS \"time\",\n       substring(head_commit_id, 1, 7) as \"short_hash\",\n       head_commit_message\nFROM push_event\nWHERE ref = \"refs/heads/master\"\nHAVING $__timeFilter(time)\nORDER BY head_commit_timestamp DESC;"
    }
   ]
  }
 ]
}