{
 "title": "GitHub Actions Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu build time gcc5.4 / py3.6",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    workflow_job.completed_at as \"time\",\n    (\n        UNIX_TIMESTAMP(workflow_job.completed_at) - UNIX_TIMESTAMP(workflow_job.started_at)\n    ) / 60 as \"runtime_minutes\"\nfrom workflow_job\n    inner join workflow_run on workflow_job.run_id = workflow_run.id\nwhere workflow_job.name = \"build\"\n    and workflow_run.name = \"linux-xenial-py3.6-gcc5.4\"\n    and workflow_job.completed_at is not null\n    and $__timeFilter(workflow_job.completed_at)\norder by workflow_job.completed_at;"
    }
   ]
  },
  {
   "title": "Execution time on master vs PR for workflow jobs",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select replace(\n        replace(replace(workflow_job.labels, \"]\", \"\"), \"[\", \"\"),\n        '\"',\n        \"\"\n    ) as \"instance\",\n    sum(\n        UNIX_TIMESTAMP(workflow_job.completed_at) - UNIX_TIMESTAMP(workflow_job.started_at)\n    ) / 60 as \"trunk_minutes\",\n    pr_query.total_minutes as \"pr_minutes\"\nfrom workflow_job\n    inner join push_event on workflow_job.head_sha = push_event.head_commit_id\n    inner join (\n        select workflow_job.labels as \"instance\",\n            sum(\n                UNIX_TIMESTAMP(workflow_job.completed_at) - UNIX_TIMESTAMP(workflow_job.started_at)\n            ) / 60 as \"total_minutes\"\n        from workflow_job\n            inner join push_event on workflow_job.head_sha = push_event.head_commit_id\n        where push_event.ref != \"refs/heads/master\"\n            and workflow_job.status = \"completed\"\n            and workflow_job.labels != \"[]\"\n            and $__timeFilter(workflow_job.completed_at)\n            and $__timeFilter(workflow_job.started_at)\n        group by workflow_job.labels\n    ) as pr_query on pr_query.instance = workflow_job.labels\nwhere push_event.ref = \"refs/heads/master\"\n    and workflow_job.status = \"completed\"\n    and workflow_job.labels != \"[]\"\n    and $__timeFilter(workflow_job.completed_at)\n    and $__timeFilter(workflow_job.started_at)\ngroup by workflow_job.labels"
    }
   ]
  },
  {
   "title": "Flaky failures",
   "type": "barchart",
   "description": "Failures on jobs that are not build / test / lint",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select CONCAT(workflow_run.name, \" / \", check_run.name) as \"name\",\n    workflow_run.id,\n    count(*) as \"failure_count\"\nfrom check_run\n    inner join workflow_run on check_run.check_suite_node_id = workflow_run.check_suite_node_id\nwhere check_run.status = \"completed\"\n    and check_run.conclusion = \"failure\"\n    and check_run.name != \"build\"\n    and check_run.name != \"build-and-test\"\n    and check_run.name not like \"test %\"\n    and check_run.name != \"test\"\n    and check_run.name != \"mypy\"\n    and check_run.name != \"quick-checks\"\n    and check_run.name != \"flake8-py3\"\n    and check_run.name != \"clang-format\"\n    and check_run.name != \"shellcheck\"\n    and check_run.name != \"clang-tidy\"\n    and $__timeFilter(check_run.completed_at)\ngroup by name\norder by count(*) desc"
    }
   ]
  },
  {
   "title": "Average Minutes per Successful Workflow Job",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(updated_at, '5m') as time,\n    SUM(\n        UNIX_TIMESTAMP(updated_at) - UNIX_TIMESTAMP(created_at)\n    ) / COUNT(*) / 60 as \"avg_runtime_minutes\",\n    name as metric\nFROM workflow_run\nWHERE status = \"completed\"\n    and conclusion = \"success\"\n    and $__timeFilter(updated_at)\nGROUP BY name,\n    time\nORDER BY time"
    }
   ]
  }
 ]
}