{
 "title": "GitHub Action Runners AWS Stats",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "# of Runners Connected",
   "type": "timeseries",
   "description": "Amount of runners connected at any single point of time to our AWS/NATGateway that are accessing Github",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "nat-08768659ec8444aed" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Avg Age of Oldest in Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "dimensions": { "QueueName": "gh-ci-queued-builds.fifo" },
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Queued builds SQS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dimensions": { "QueueName": "gh-ci-queued-builds.fifo" },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "gh-ci-queued-builds.fifo" },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Number of messages visible and non-visible in queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "QueueName": "gh-ci-queued-builds.fifo" },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "gh-ci-queued-builds.fifo" },
     "metricName": "ApproximateNumberOfMessagesNotVisible",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Number of messages delayed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "QueueName": "gh-ci-queued-builds.fifo" },
     "metricName": "ApproximateNumberOfMessagesDelayed",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Github Runners CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "metricName": "CPUUtilization", "namespace": "AWS/EC2", "region": "us-east-1", "statistic": "Average" }
   ]
  }
 ]
}