{
 "title": "PyTorch Domination",
 "time": { "from": "2021-09-10T07:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "PyTorch Contributors (7days total) (in vs out of Meta)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(commit_committer_date, '7d'),\n  COUNT(DISTINCT IF(commit_committer_email LIKE \"%fb.com\" OR commit_committer_email LIKE \"%facebook%\", commit_committer_email, null)) as total_meta_contributors,\n  COUNT(DISTINCT IF(commit_committer_email NOT LIKE \"%fb.com\" AND commit_committer_email NOT LIKE \"%facebook%\", commit_committer_email, null)) as total_out_of_meta_contributors\nFROM commit\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "PyTorch Contributors (mails) 1w",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(commit_committer_date, '7d'),\n  COUNT(DISTINCT IF(commit_committer_email LIKE \"%fb.com\" OR commit_committer_email LIKE \"%facebook%\", commit_committer_email, null)) as total_meta_contributors,\n  COUNT(DISTINCT IF(commit_committer_email NOT LIKE \"%fb.com\" AND commit_committer_email NOT LIKE \"%facebook%\", commit_committer_email, null)) as total_out_of_meta_contributors\nFROM commit\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "# Of Commits Per 7 Days",
   "type": "timeseries",
   "description": "Amount of commits from different contributors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(commit_committer_date, '7d'),\n  SUM(IF(commit_committer_email LIKE \"%fb.com\" OR commit_committer_email LIKE \"%facebook%\", 1, 0)) as from_meta,\n  SUM(IF(commit_committer_email NOT LIKE \"%fb.com\" AND commit_committer_email NOT LIKE \"%facebook%\", 1, 0)) as not_from_meta,\n  COUNT(commit_committer_email) as total\nFROM commit\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "% Of Commits From Meta vs Out-of Meta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(commit_committer_date, '7d'),\n  SUM(IF(commit_committer_email LIKE \"%fb.com\" OR commit_committer_email LIKE \"%facebook%\", 1, 0)) as from_meta,\n  SUM(IF(commit_committer_email NOT LIKE \"%fb.com\" AND commit_committer_email NOT LIKE \"%facebook%\", 1, 0)) as not_from_meta\nFROM commit\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Commits Counts Per Company (All Time)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  IF(commit_committer_email LIKE \"%facebook%\" OR commit_committer_email LIKE \"%fb.com\" OR commit_committer_email LIKE \"=\",\n    \"meta / FB\",\n    SUBSTRING(commit_committer_email, LOCATE('@', commit_committer_email) + 1, LENGTH(commit_committer_email))\n    ) company,\n  COUNT(IF(commit_committer_email LIKE \"%facebook%\" OR commit_committer_email LIKE \"%fb.com\" OR commit_committer_email LIKE \"=\",\n    \"meta / FB\",\n    SUBSTRING(commit_committer_email, LOCATE('@', commit_committer_email) + 1, LENGTH(commit_committer_email))\n    )) as commits_count\nFROM commit\nGROUP BY company\nORDER BY commits_count DESC"
    }
   ]
  },
  {
   "title": "Companies Contributing During 1w",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroupAlias(commit_committer_date, '7d'),\n    COUNT(DISTINCT \n      IF(\n        commit_committer_email LIKE \"%facebook%\" OR commit_committer_email LIKE \"%fb.com\" OR commit_committer_email LIKE \"=\",\n        \"meta\",\n        IF (\n          commit_committer_email LIKE \"%gmail.com%\" OR commit_committer_email LIKE \"%live.co.uk%\" OR commit_committer_email LIKE \"%hotmail.com%\" OR commit_committer_email LIKE \"%outlook.com%\" OR commit_committer_email LIKE \"%live.com%\",\n          \"personal\",\n          SUBSTRING(commit_committer_email, LOCATE('@', commit_committer_email) + 1, LENGTH(commit_committer_email))\n        )\n      )) as companies_count\nFROM commit\nGROUP BY time\nORDER BY time DESC"
    }
   ]
  }
 ]
}