{
 "title": "Recycle Bin",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Execution time on master vs PR for workflow jobs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select replace(\n        replace(replace(workflow_job.labels, \"]\", \"\"), \"[\", \"\"),\n        '\"',\n        \"\"\n    ) as \"instance\",\n    sum(\n        UNIX_TIMESTAMP(workflow_job.completed_at) - UNIX_TIMESTAMP(workflow_job.started_at)\n    ) / 60 as \"trunk_minutes\",\n    pr_query.total_minutes as \"pr_minutes\"\nfrom workflow_job\n    inner join push_event on workflow_job.head_sha = push_event.head_commit_id\n    inner join (\n        select workflow_job.labels as \"instance\",\n            sum(\n                UNIX_TIMESTAMP(workflow_job.completed_at) - UNIX_TIMESTAMP(workflow_job.started_at)\n            ) / 60 as \"total_minutes\"\n        from workflow_job\n            inner join push_event on workflow_job.head_sha = push_event.head_commit_id\n        where push_event.ref != \"refs/heads/master\"\n            and workflow_job.status = \"completed\"\n            and workflow_job.labels != \"[]\"\n            and $__timeFilter(workflow_job.completed_at)\n            and $__timeFilter(workflow_job.started_at)\n        group by workflow_job.labels\n    ) as pr_query on pr_query.instance = workflow_job.labels\nwhere push_event.ref = \"refs/heads/master\"\n    and workflow_job.status = \"completed\"\n    and workflow_job.labels != \"[]\"\n    and $__timeFilter(workflow_job.completed_at)\n    and $__timeFilter(workflow_job.started_at)\ngroup by workflow_job.labels"
    }
   ]
  },
  {
   "title": "Average Build/Test Run Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(t1.sync_last_update_at, 30m),\n       avg((unix_timestamp(t2.sync_last_update_at) - unix_timestamp(t1.sync_last_update_at)) / 60) \"windows build (m)\"\nFROM\n  (SELECT dense_rank() over(PARTITION BY BINARY workflow_job_node_id\n                            ORDER BY sync_last_update_at) AS \"rerun_num\",\n          action,\n          workflow_job_node_id,\n          sync_last_update_at\n   FROM workflow_job_event\n   WHERE action = \"in_progress\"\n     AND $__timeFilter(sync_last_update_at) ) AS t1\nINNER JOIN\n  (SELECT dense_rank() over(PARTITION BY BINARY workflow_job_node_id\n                            ORDER BY sync_last_update_at) AS \"rerun_num\",\n          action,\n          workflow_job_node_id,\n          sync_last_update_at\n   FROM workflow_job_event\n   WHERE action = \"completed\"\n     AND $__timeFilter(sync_last_update_at) ) AS t2 ON t1.rerun_num = t2.rerun_num\nAND t1.workflow_job_node_id = t2.workflow_job_node_id\nAND t1.sync_last_update_at < t2.sync_last_update_at\nINNER JOIN workflow_job ON workflow_job.node_id = t1.workflow_job_node_id\nINNER JOIN workflow_run ON workflow_job.run_id = workflow_run.id\nWHERE workflow_job.name like \"%build%\" and workflow_run.name like \"%win%\" and workflow_job.name != \"generate-test-matrix\" and workflow_job.conclusion = \"success\"\nGROUP BY 1\nORDER BY $__timeGroup(t1.sync_last_update_at, 30m)"
    },
    {
     "rawSql": "SELECT $__timeGroupAlias(t1.sync_last_update_at, 30m),\n       avg((unix_timestamp(t2.sync_last_update_at) - unix_timestamp(t1.sync_last_update_at)) / 60) \"windows test (m)\"\nFROM\n  (SELECT dense_rank() over(PARTITION BY BINARY workflow_job_node_id\n                            ORDER BY sync_last_update_at) AS \"rerun_num\",\n          action,\n          workflow_job_node_id,\n          sync_last_update_at\n   FROM workflow_job_event\n   WHERE action = \"in_progress\"\n     AND $__timeFilter(sync_last_update_at) ) AS t1\nINNER JOIN\n  (SELECT dense_rank() over(PARTITION BY BINARY workflow_job_node_id\n                            ORDER BY sync_last_update_at) AS \"rerun_num\",\n          action,\n          workflow_job_node_id,\n          sync_last_update_at\n   FROM workflow_job_event\n   WHERE action = \"completed\"\n     AND $__timeFilter(sync_last_update_at) ) AS t2 ON t1.rerun_num = t2.rerun_num\nAND t1.workflow_job_node_id = t2.workflow_job_node_id\nAND t1.sync_last_update_at < t2.sync_last_update_at\nINNER JOIN workflow_job ON workflow_job.node_id = t1.workflow_job_node_id\nINNER JOIN workflow_run ON workflow_job.run_id = workflow_run.id\nWHERE workflow_job.name like \"%test%\" and workflow_run.name like \"%win%\" and workflow_job.name != \"generate-test-matrix\" and workflow_job.conclusion = \"success\"\nGROUP BY 1\nORDER BY $__timeGroup(t1.sync_last_update_at, 30m)"
    },
    {
     "rawSql": "SELECT $__timeGroupAlias(t1.sync_last_update_at, 30m),\n       avg((unix_timestamp(t2.sync_last_update_at) - unix_timestamp(t1.sync_last_update_at)) / 60) \"linux build (m)\"\nFROM\n  (SELECT dense_rank() over(PARTITION BY BINARY workflow_job_node_id\n                            ORDER BY sync_last_update_at) AS \"rerun_num\",\n          action,\n          workflow_job_node_id,\n          sync_last_update_at\n   FROM workflow_job_event\n   WHERE action = \"in_progress\"\n     AND $__timeFilter(sync_last_update_at) ) AS t1\nINNER JOIN\n  (SELECT dense_rank() over(PARTITION BY BINARY workflow_job_node_id\n                            ORDER BY sync_last_update_at) AS \"rerun_num\",\n          action,\n          workflow_job_node_id,\n          sync_last_update_at\n   FROM workflow_job_event\n   WHERE action = \"completed\"\n     AND $__timeFilter(sync_last_update_at) ) AS t2 ON t1.rerun_num = t2.rerun_num\nAND t1.workflow_job_node_id = t2.workflow_job_node_id\nAND t1.sync_last_update_at < t2.sync_last_update_at\nINNER JOIN workflow_job ON workflow_job.node_id = t1.workflow_job_node_id\nINNER JOIN workflow_run ON workflow_job.run_id = workflow_run.id\nWHERE workflow_job.name like \"%build%\" and workflow_run.name like \"%linux%\"  and workflow_job.name != \"generate-test-matrix\" and workflow_job.conclusion = \"success\"\nGROUP BY 1\nORDER BY $__timeGroup(t1.sync_last_update_at, 30m)"
    },
    {
     "rawSql": "SELECT $__timeGroupAlias(t1.sync_last_update_at, 30m),\n       avg((unix_timestamp(t2.sync_last_update_at) - unix_timestamp(t1.sync_last_update_at)) / 60) \"linux test (m)\"\nFROM\n  (SELECT dense_rank() over(PARTITION BY BINARY workflow_job_node_id\n                            ORDER BY sync_last_update_at) AS \"rerun_num\",\n          action,\n          workflow_job_node_id,\n          sync_last_update_at\n   FROM workflow_job_event\n   WHERE action = \"in_progress\"\n     AND $__timeFilter(sync_last_update_at) ) AS t1\nINNER JOIN\n  (SELECT dense_rank() over(PARTITION BY BINARY workflow_job_node_id\n                            ORDER BY sync_last_update_at) AS \"rerun_num\",\n          action,\n          workflow_job_node_id,\n          sync_last_update_at\n   FROM workflow_job_event\n   WHERE action = \"completed\"\n     AND $__timeFilter(sync_last_update_at) ) AS t2 ON t1.rerun_num = t2.rerun_num\nAND t1.workflow_job_node_id = t2.workflow_job_node_id\nAND t1.sync_last_update_at < t2.sync_last_update_at\nINNER JOIN workflow_job ON workflow_job.node_id = t1.workflow_job_node_id\nINNER JOIN workflow_run ON workflow_job.run_id = workflow_run.id\nWHERE workflow_job.name like \"%test%\" and workflow_run.name like \"%linux%\" and workflow_job.name != \"generate-test-matrix\" and workflow_job.conclusion = \"success\"\nGROUP BY 1\nORDER BY $__timeGroup(t1.sync_last_update_at, 30m)"
    }
   ]
  },
  {
   "title": "Average Queue Time (GHA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(t1.sync_last_update_at, 30m),\n       avg((unix_timestamp(t2.sync_last_update_at) - unix_timestamp(t1.sync_last_update_at)) / 60) \"queue_time (m)\"\nFROM\n  (SELECT dense_rank() over(PARTITION BY BINARY workflow_job_node_id\n                            ORDER BY sync_last_update_at) AS \"rerun_num\",\n          action,\n          workflow_job_node_id,\n          sync_last_update_at\n   FROM workflow_job_event\n   WHERE action = \"queued\"\n     AND $__timeFilter(sync_last_update_at) ) AS t1\nINNER JOIN\n  (SELECT dense_rank() over(PARTITION BY BINARY workflow_job_node_id\n                            ORDER BY sync_last_update_at) AS \"rerun_num\",\n          action,\n          workflow_job_node_id,\n          sync_last_update_at\n   FROM workflow_job_event\n   WHERE action = \"in_progress\"\n     AND $__timeFilter(sync_last_update_at) ) AS t2 ON t1.rerun_num = t2.rerun_num\nAND t1.workflow_job_node_id = t2.workflow_job_node_id\nAND t1.sync_last_update_at < t2.sync_last_update_at\nGROUP BY 1\nORDER BY $__timeGroup(t1.sync_last_update_at, 30m)"
    }
   ]
  },
  {
   "title": "GitHub Actions Master Fail %",
   "type": "timeseries",
   "description": "Failures on GHA runs on the master branch",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT time,\n       failing_jobs / (failing_jobs + passing_jobs) * 100 as \"Fail Percent\"\nFROM\n  (SELECT $__timeGroupAlias(workflow_job.completed_at, 30m),\n          sum(CASE\n                  WHEN workflow_job.conclusion != \"success\"\n                       AND workflow_job.conclusion != \"skipped\"\n                       AND workflow_job.conclusion != \"cancelled\" THEN 1\n                  ELSE 0\n              END) AS failing_jobs,\n          sum(CASE\n                  WHEN workflow_job.conclusion = \"success\" THEN 1\n                  ELSE 0\n              END) AS passing_jobs\n   FROM workflow_job\n   INNER JOIN workflow_run ON workflow_job.run_id = workflow_run.id\n   WHERE workflow_run.head_branch = \"master\"\n     AND $__timeFilter(workflow_job.completed_at)\n   GROUP BY 1\n   ORDER BY $__timeGroup(completed_at, 30m)) AS nested"
    }
   ]
  },
  {
   "title": "Last nightly update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select\n  ref,\n  head_commit_message, (UNIX_TIMESTAMP(CURRENT_TIMESTAMP()) - 25200 - UNIX_TIMESTAMP(head_commit_timestamp)) / 60 / 60 as \"hours_since_push\"\nfrom push_event\nwhere ref='refs/heads/nightly' and (head_commit_added!=\"[]\" or head_commit_removed!=\"[]\" or head_commit_modified!=\"[]\")\norder by head_commit_timestamp desc \nlimit 1;"
    }
   ]
  },
  {
   "title": "Last viable/strict update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select\n  ref,\n  head_commit_message, (UNIX_TIMESTAMP(CURRENT_TIMESTAMP()) - 25200 - UNIX_TIMESTAMP(head_commit_timestamp)) / 60 / 60 as \"hours_since_push\"\nfrom push_event\nwhere ref='refs/heads/viable/strict' and (head_commit_added!=\"[]\" or head_commit_removed!=\"[]\" or head_commit_modified!=\"[]\")\norder by head_commit_timestamp desc \nlimit 1;"
    }
   ]
  },
  {
   "title": "# Reverts",
   "type": "stat",
   "description": "Note: Bundled commits show up as a single revert",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"num_reverts\"\nfrom push_event\nwhere ref = 'refs/heads/master'\n    and head_commit_message like \"Revert D%\"\n    and $__timeFilter(sync_last_update_at);"
    }
   ]
  },
  {
   "title": "Last master update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select\n  ref,\n  head_commit_message, (UNIX_TIMESTAMP(CURRENT_TIMESTAMP()) - 25200 - UNIX_TIMESTAMP(head_commit_timestamp)) / 60 / 60 as \"hours_since_push\"\nfrom push_event\nwhere ref='refs/heads/master'\norder by head_commit_timestamp desc \nlimit 1;"
    }
   ]
  },
  {
   "title": "CircleCI/Jenkins Master Fail %",
   "type": "timeseries",
   "description": "Failures on CircleCI runs on the master branch",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT time,\n       failing_jobs / (failing_jobs + passing_jobs) * 100 as \"fail_percent\"\nFROM\n  (SELECT $__timeGroupAlias(updated_at, 30m),\n          sum(CASE\n                  WHEN state != \"success\"\n                       AND state != \"pending\" THEN 1\n                  ELSE 0\n              END) AS failing_jobs,\n          sum(CASE\n                  WHEN state = \"success\" THEN 1\n                  ELSE 0\n              END) AS passing_jobs\n   FROM status_event\n   WHERE $__timeFilter(updated_at)\n     AND json_unquote(json_extract(branches, \"$[0].name\")) = \"master\"\n   GROUP BY 1\n   ORDER BY $__timeGroup(updated_at, 30m)) AS nested"
    }
   ]
  }
 ]
}