{
 "title": "Squid Cached Proxy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests Count (30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancerName": "tf-lb-20210727220640487900000002"
     },
     "metricName": "RequestCount",
     "namespace": "AWS/ELB",
     "period": "30",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancerName": "tf-lb-20210727220640487900000002"
     },
     "metricName": "Latency",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Healthy Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancerName": "tf-lb-20210727220640487900000002"
     },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ELB",
     "period": "30s",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "LoadBalancerName": "tf-lb-20210727220640487900000002"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "period": "30s",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Backend Connection Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancerName": "tf-lb-20210727220640487900000002"
     },
     "metricName": "BackendConnectionErrors",
     "namespace": "AWS/ELB",
     "period": "30s",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}