name: Disable Flaky Tests

on:
  schedule:
    # At minute 39 past every 6th hour Monday through Friday.
    - cron: "39 */6 * * 1-5"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Fetch and file issues for flaky tests
        env:
          FLAKY_TEST_BOT_KEY: ${{ secrets.FLAKY_TEST_BOT_KEY }}
          HUD_API_TOKEN: ${{ secrets.HUD_API_TOKEN }}
        run: python .github/scripts/disable_flaky_tests.py
