name: Disable Flaky Tests

on:
  schedule:
    # At minute 39 past every 6th hour Monday through Friday.
    - cron: "39 */6 * * 1-5"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-22.04
    environment: hud
    steps:
      - uses: actions/checkout@v4
      - name: Fetch and file issues for flaky tests
        env:
          FLAKY_TEST_BOT_KEY: ${{ secrets.FLAKY_TEST_BOT_KEY }}
          X_HUD_BOT_TOKEN: ${{ secrets.X_HUD_BOT_TOKEN }}
        run: python .github/scripts/disable_flaky_tests.py
